### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by hainingbaby** [polyvios/locksmith#1]
Dear Polyvios,
Hello, sorry to bother you. I want try LockSmith to detect data race,  but i have trouble in installation.
I have installed Ocaml 4.05  CIL 0.07  and Banshee, but when I run `./configure` , 
 at the end it shows like this:

> config.status: config.h is unchanged
> CIL configuration:
>   architecture/OS:            ARCHOS             x86_LINUX
>   source tree root:           CILHOME            /home/haining/data-race-tool/locksmith-1.0/cil
>   (optional) cl.exe found:    HAS_MSVC           no
>   gcc to use                  CC                 gcc
>   default compiler            DEFAULT_COMPILER   _GNUCC
>   CIL version                 CIL_VERSION        1.3.7
>   CIL features                CIL_FEATURES        locksmith lockpick stmizer
>   Extra source directories    EXTRASRCDIRS       /home/haining/data-race-tool/locksmith-1.0/src
>   Cycles per microsecond      CYCLES_PER_USEC    0
> sed: -e expression #1, char 49: number option to `s' command may not be zero
> sed: -e expression #1, char 49: number option to `s' command may not be zero

And when I run `make`, it shows:

> make[1]: Entering directory '/home/haining/data-race-tool/locksmith-1.0/banshee'
> make -C libcompat
> make[2]: Entering directory '/home/haining/data-race-tool/locksmith-1.0/banshee/libcompat'
> cc -c -Wall -Ddeletes="" -DNMEMDEBUG -DNDEBUG -Werror -fno-common -o regions.o regions.c
> In file included from regions.c:111:0:
> pages.c: In function ‘set_region_range’:
> pages.c:332:3: error: this ‘while’ clause does not guard... [-Werror=misleading-indentation]
>    while (firstm < lastm || firstp <= lastp)
>    ^~~~~
> pages.c:337:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘while’
>      set_page_region(firstm, firstp++, r);
>      ^~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> Makefile:43: recipe for target 'regions.o' failed
> make[2]: *** [regions.o] Error 1
> make[2]: Leaving directory '/home/haining/data-race-tool/locksmith-1.0/banshee/libcompat'
> Makefile:41: recipe for target 'libcompat' failed
> make[1]: *** [libcompat] Error 2
> make[1]: Leaving directory '/home/haining/data-race-tool/locksmith-1.0/banshee'
> Makefile:47: recipe for target 'all' failed
> make: *** [all] Error 2
> 
The tool is excellent, and I really want to have a try, Can you help me see what went wrong?
I'd appreciate it greatly if you can give me some guides.

Best,
Haining

**Comment by polyvios** [comment]
Dear Haining,

Thanks for your interest!
Truth is I haven't worked on maintaining it in quite a while, so I'm not 
sure how it works with newer compilers.

The ./configure error is not important, probably because the "." 
character in the "pwd" path confuses sed.  You can safely ignore it, and 
manually create the "locksmith" and "lockpick" scripts from the 
"locksmith.in" and "lockpick.in" template files, or change the replace 
expression character in the configure script to use something else, say 
"'" or ",".  Compilation configuration is done by that line in the 
script so it shouldn't make any difference in compiling.

As to the error with make, it seems gcc now check indentation issues.  I 
tried to port banshee to 64-bit pointers (it has its own memory 
allocator which was 32-bit) but didn't do anything else to maintain its 
code. Taking a look at the offending lines, there are braces around line 
337, so I'm not getting that error.  Are you sure you have checked out 
the latest commit?  The locksmith github repository includes its own 
banshee port (for 64-bit).

I was able to configure & compile a fresh git clone just now with ocaml 
4.05.0 and gcc 5.4.0 and 7.4.0 (both worked).
Hope this helps, let me know if there are any other issues.
Polyvios

**Comment by hainingbaby** [comment]
Dear Polyvios,
Thanks for your patiently reply , Very much! 
At the beginning, I modified some syntax details in the source code, but it still didn't work. I was downloaded it from _LockSmith_'s website.
Then I tried the version from this repo. **It works**.
Thank you very much, again!
I think _LockSmith_ is really a good tool detecting data-race. 

And can I ask you a question again?  **Now for detecting data-race problem, which tools dou you think  are better? Can you recommend me a few**?
Forgive me for my poor English，thank you again !

Best,
Haining
